dependencies:
  - role: dataset_dbpedia2015
  - role: dataset_swdf
  - role: dataset_watdiv
  - role: dataset_wikidata-20201111
  - role: tentris
  - role: fuseki
  - role: gstore
  - role: virtuoso
  - role: graphdb
  - role: blazegraph
  - role: loaders
  - role: iguana
  - role: iguana_suites
