- name: Ensure Jena Directory is present
  file:
    path: "{{ target_dir }}/triplestores/jena"
    state: directory

- name: Create a tempory download directory
  tempfile:
    state: directory
    suffix: jena
  register: tempdir

- name: Download Jena Checksum
  get_url:
    url: https://www.apache.org/dist/jena/binaries/apache-jena-{{ jena_version }}.tar.gz.sha512
    dest: "{{ tempdir.path }}/apache-jena-{{ jena_version }}.tar.gz.sha512"

- name: Slurp Jena Checksum
  slurp:
    path: "{{ tempdir.path }}/apache-jena-{{ jena_version }}.tar.gz.sha512"
  register: checksum

- name: Download Jena
  get_url:
    url: http://www.apache.org/dist/jena/binaries/apache-jena-{{ jena_version }}.tar.gz
    checksum: "sha512:{{ (checksum.content | b64decode).split(' ')[0] }}"
    dest: "{{ tempdir.path }}/apache-jena-{{ jena_version }}.tar.gz"

- name: Unzip Jena
  unarchive:
    remote_src: yes
    src: "{{ tempdir.path }}/apache-jena-{{ jena_version }}.tar.gz"
    dest: "{{ target_dir }}/triplestores/jena/"

- name: Delete tempdir
  file:
    path: "{{ tempdir.path }}"
    state: absent
