- name: Check for GraphDB
  stat:
    path: "{{ target_dir }}/triplestores/graphdb/graphdb-free-{{ graphdb_version }}/"
  register: graphdb_dir

- include: install.yaml
  when: not graphdb_dir.stat.exists
